Carga de base de datos desde postgres (utilizando Docker).

In [ ]:
from sqlalchemy import create_engine
engine = create_engine('postgresql://postgres:practica@localhost:5432/postgres')
df = pd.read_sql("SELECT * FROM events", engine)

#Configuración de formato de despliegue
pd.set_option('display.float_format', lambda x: f'{x:,.2f}')

In [14]:
df.head()

,event_time,event_type,product_id,category_id,category_code,brand,price,user_id,user_session
0,2019-10-01 00:00:25+00:00,view,19001139,2053013557225718275,NaN,gran-stone,67.58,525734504,83f584ed-c7f7-442e-8ae9-713cb27fdece
1,2019-10-01 00:00:50+00:00,view,19000296,2053013557225718275,NaN,gran-stone,64.93,525734504,83f584ed-c7f7-442e-8ae9-713cb27fdece
2,2019-10-01 00:00:58+00:00,view,4802639,2053013554658804075,electronics.audio.headphone,sony,218.77,514808401,1877639d-46a4-44f8-bae9-a14456952240
3,2019-10-01 00:01:07+00:00,view,27700113,2053013560086233771,construction.tools.pump,leo,48.90,515630204,f9cc0313-5572-4894-a4eb-45d855f064cc
4,2019-10-01 00:01:11+00:00,view,1004836,2053013555631882655,electronics.smartphone,samsung,241.19,546259103,6e2984c8-502e-4fe7-bbba-34087f760175

In [6]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 2103521 entries, 0 to 2103520
Data columns (total 9 columns):
 #   Column         Dtype
---  ------         -----
 0   event_time     datetime64[us, UTC]
 1   event_type     str
 2   product_id     int64
 3   category_id    int64
 4   category_code  str
 5   brand          str
 6   price          float64
 7   user_id        int64
 8   user_session   str
dtypes: datetime64[us, UTC](1), float64(1), int64(3), str(4)
memory usage: 144.4 MB

In [16]:
df.describe()

         product_id                  category_id        price        user_id
count  2,103,521.00                 2,103,521.00 2,103,521.00   2,103,521.00
mean  10,625,751.86 2,057,403,318,225,317,376.00       289.09 533,652,796.94
std   11,903,960.22    18,408,762,032,224,496.00       356.80  18,467,618.29
min    1,000,978.00 2,053,013,552,226,107,648.00         0.00 269,228,602.00
25%    1,005,157.00 2,053,013,555,464,110,592.00        65.38 516,051,600.00
50%    5,100,337.00 2,053,013,555,631,882,752.00       161.91 530,029,202.00
75%   16,200,121.00 2,053,013,563,307,459,328.00       358.44 551,629,200.00
max   60,500,007.00 2,175,419,595,093,967,616.00     2,574.07 566,279,704.00

In [24]:
df.isna().sum()

event_time            0
event_type            0
product_id            0
category_id           0
category_code    679795
brand            303436
price                 0
user_id               0
user_session          0
dtype: int64

In [27]:
df['event_type'].value_counts()

event_type
view        2019379
cart          47156
purchase      36986
Name: count, dtype: int64